### ISSUE TITLE
Failed recurring payment

### ISSUE THREAD

**Issue by jethromayuk** [wallee-payment/woocommerce-subscription#2]
Recurring payments don't seem to be working at the moment... What information do you require me to send through?

Additionally the plugin seems to be throwing this error:

```
2022-06-29T09:13:59+00:00 CRITICAL Uncaught Error: Call to a member function getPaymentMethodConfiguration() on null in /nas/content/live/****/wp-content/plugins/woo-wallee/includes/service/class-wc-wallee-service-token.php:80
Stack trace:
#0 /nas/content/live/****/wp-content/plugins/woo-wallee/includes/service/class-wc-wallee-service-token.php(34): WC_Wallee_Service_Token->update_info(29212, Object(Wallee\Sdk\Model\TokenVersion))
#1 /nas/content/live/****/wp-content/plugins/woo-wallee/includes/webhook/class-wc-wallee-webhook-token-version.php(20): WC_Wallee_Service_Token->update_token_version(29212, 1679921)
#2 /nas/content/live/****/wp-content/plugins/woo-wallee/includes/class-wc-wallee-webhook-handler.php(55): WC_Wallee_Webhook_Token_Version->process(Object(WC_Wallee_Webhook_Request))
#3 /nas/content/live/****/wp-includes/class-wp-hook.php(307): WC_Wallee_Webhook_Handler::process('')
#4 /nas/content/live/****/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
#5  in /nas/content/live/****/wp-content/plugins/woo-wallee/includes/service/class-wc-wallee-service-token.php on line 80
```

**Comment by jethromayuk** [comment]
Not sure if this is relevant:

<img width="615" alt="Screenshot 2022-06-29 at 10 30 10" src="https://user-images.githubusercontent.com/6702147/176403372-f641aca5-47a3-47a7-a283-1dcbf6580f1f.png">

**Comment by theodorspringwallee** [comment]
Hello [jethromayuk](https://github.com/jethromayuk), It seems the token version can't be loaded anymore for the concerned subscription. This is why the payment connector configuration is called on null instead of the missing token version.

Please can you contact our support directly via **info@wallee.com**, since it seems to be an individual issue.
At best, please provide for the support your space ID, the concerned subscription (wallee & shop backend links) as well your shop backend data that they can check.

Our support can also reproduce your issue on our test systems, in case it would be a BUG.

Therefore, I will close this git issue chat.
