### ISSUE TITLE
Call to a member function get_coupon_discount_totals() on null

### ISSUE THREAD

**Issue by scottybo** [wallee-payment/woocommerce-subscription#3]
Hi guys, we are getting the error:

`Call to a member function get_coupon_discount_totals() on null`

The stacktrace is:

```
03-26-2023 @ 22:56:55 - scheduled action 103717 (subscription payment) failed to finish processing due to the following error: Uncaught Error: Call to a member function get_coupon_discount_totals() on null in /var/web/site/public_html/wp-content/plugins/woo-wallee/includes/packages/coupon/class-wc-wallee-packages-coupon-discount.php:104
Stack trace:
#0 /var/web/site/public_html/wp-includes/class-wp-hook.php(308): WC_Wallee_Packages_Coupon_Discount::get_coupons_discount_totals_including_tax('GBP')
#1 /var/web/site/public_html/wp-includes/plugin.php(205): WP_Hook->apply_filters('GBP', Array)
#2 /var/web/site/public_html/wp-content/plugins/woo-wallee/includes/packages/coupon/class-wc-wallee-packages-coupon-discount.php(118): apply_filters('wc_wallee_packa...', 'GBP')
#3 /var/web/site/public_html/wp-includes/class-wp-hook.php(308): WC_Wallee_Packages_Coupon_Discount::has_cart_coupon_discounts_applied('GBP')
#4 /var/web/site/public_html/wp-includes/plugin.php(205): WP_Hook->apply_filters('GBP', Array)
#5 /var/web/site/public_html/wp-content/plugins/woo-wallee/includes/class-wc-wallee-helper.php(238): apply_filters('wc_wallee_packa...', 'GBP')
#6 /var/web/site/public_html/wp-content/plugins/woo-wallee-subscription/includes/service/class-wc-wallee-subscription-service-transaction.php(93): WC_Wallee_Helper->cleanup_line_items(Array, '4.99', 'GBP')
#7 /var/web/site/public_html/wp-content/plugins/woo-wallee-subscription/includes/service/class-wc-wallee-subscription-service-transaction.php(43): WC_Wallee_Subscription_Service_Transaction->set_modified_order_line_items(Object(Automattic\WooCommerce\Admin\Overrides\Order), '4.99', Object(Wallee\Sdk\Model\TransactionCreate))
#8 /var/web/site/public_html/wp-content/plugins/woo-wallee-subscription/includes/class-wc-wallee-subscription-gateway.php(123): WC_Wallee_Subscription_Service_Transaction->create_transaction_by_renewal_order(Object(Automattic\WooCommerce\Admin\Overrides\Order), '4.99', '2713886')
#9 /var/web/site/public_html/wp-includes/class-wp-hook.php(308): WC_Wallee_Subscription_Gateway->process_scheduled_subscription_payment('4.99', Object(Automattic\WooCommerce\Admin\Overrides\Order))
#10 /var/web/site/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#11 /var/web/site/public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#12 /var/web/site/public_html/wp-content/plugins/woocommerce-subscriptions/includes/gateways/class-wc-subscriptions-payment-gateways.php(222): do_action('woocommerce_sch...', '4.99', Object(Automattic\WooCommerce\Admin\Overrides\Order))
#13 /var/web/site/public_html/wp-content/plugins/woocommerce-subscriptions/includes/gateways/class-wc-subscriptions-payment-gateways.php(250): WC_Subscriptions_Payment_Gateways::trigger_gateway_renewal_payment_hook(Object(Automattic\WooCommerce\Admin\Overrides\Order))
#14 /var/web/site/public_html/wp-includes/class-wp-hook.php(308): WC_Subscriptions_Payment_Gateways::gateway_scheduled_subscription_payment(20133)
#15 /var/web/site/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#16 /var/web/site/public_html/wp-includes/plugin.php(565): WP_Hook->do_action(Array)
#17 /var/web/site/public_html/wp-content/plugins/mailchimp-for-woocommerce/includes/vendor/action-scheduler/classes/actions/ActionScheduler_Action.php(43): do_action_ref_array('woocommerce_sch...', Array)
#18 /var/web/site/public_html/wp-content/plugins/mailchimp-for-woocommerce/includes/vendor/action-scheduler/classes/abstracts/ActionScheduler_Abstract_QueueRunner.php(65): ActionScheduler_Action->execute()
#19 /var/web/site/public_html/wp-content/plugins/mailchimp-for-woocommerce/includes/vendor/action-scheduler/classes/ActionScheduler_QueueRunner.php(166): ActionScheduler_Abstract_QueueRunner->process_action(103717, 'WP Cron')
#20 /var/web/site/public_html/wp-content/plugins/mailchimp-for-woocommerce/includes/vendor/action-scheduler/classes/ActionScheduler_QueueRunner.php(136): ActionScheduler_QueueRunner->do_batch(25, 'WP Cron')
#21 /var/web/site/public_html/wp-includes/class-wp-hook.php(308): ActionScheduler_QueueRunner->run('WP Cron')
#22 /var/web/site/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#23 /var/web/site/public_html/wp-includes/plugin.php(565): WP_Hook->do_action(Array)
#24 /var/web/site/public_html/wp-cron.php(188): do_action_ref_array('action_schedule...', Array)
#25 {main}
  thrown
03-26-2023 @ 22:56:55 - action args: subscription_id: 20133```

Please can you advise on how to rectify this?

**Comment by theodorspringwallee** [comment]
Dear [scottybo](https://github.com/scottybo)

It seems, that we have an incompatibility here, because of the Smart Coupon compatibility we have added to our plugin in the version 2.1.9. 

This has broken the subscription plugin in some way.

Please, can you downgrade the Wallee/WooCommerce plugin in the meanwhile to 2.1.8: https://github.com/wallee-payment/woocommerce/releases

We will let you know, when we have fixed this issue.

Best regards

**Comment by scottybo** [comment]
Thanks for the speedy reply - do you know when a fix will be available?

**Comment by theodorspringwallee** [comment]
Dear [scottybo](https://github.com/scottybo)

You can install now the newest plugin version of wallee/woocommerce, what should fix the mentioned issue: https://github.com/wallee-payment/woocommerce/releases

Best regards
